### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ah0lx** [complexpotato/Faitagram#116] opened 2019-03-19 18:36 UTC
**python setup.py**       
File "setup.py", line 42
chmod +x faitagram && chmod +x setup.py
                     ^
SyntaxError: invalid syntax

**Comment by daniel071** [comment] 2019-04-15 12:53
Duplicate of #109 'Error setup.py' but that doesn't seem to have been resolved either.
It seems like the developer has dropped support for this issue

**Comment by 44za12** [comment] 2019-05-07 13:42
Removing the line fixed the issue for me. The syntax of the code in line 42 is bash, and it's written in python. Delete the line and then try to run it. You can manually change the permissions of files faitagram.

**Comment by daniel071** [comment] 2019-05-08 08:16
> Removing the line fixed the issue for me. The syntax of the code in line 42 is bash, and it's written in python. Delete the line and then try to run it. You can manually change the permissions of files faitagram.

You can also see that the pull requests, #114 and #113 have done the same thing.
Thanks!

**Closed** 2021-05-24 18:53 UTC
